# Generated by Django 4.0.6 on 2022-07-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshub', '0004_profile_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
