# Generated by Django 4.0.6 on 2022-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshub', '0005_alter_profile_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='mesUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_No', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
    ]
