# Generated by Django 4.0.6 on 2022-07-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshub', '0006_mesusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesusers',
            name='id_No',
            field=models.CharField(max_length=100),
        ),
    ]
